# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
  libc-0.2.101
  winapi-0.3.9
  winapi-i686-pc-windows-gnu-0.4.0
  winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="A simple Git/Hg version control client based on keyboard shortcuts"
HOMEPAGE="https://github.com/matheuslessarodrigues/verco"
SRC_URI="
  https://github.com/vamolessa/${PN}/archive/refs/tags/v${PV}.tar.gz
  $(cargo_crate_uris ${CRATES})"

LICENSE="Apache-2.0 GPL-3.0 MIT"
SLOT="0"
KEYWORDS="amd64"
RESTRICT="mirror"
