#!/usr/bin/env bash

if [[ $(id -u) == 0 ]]; then
  echo "grabber: Unable to start as root, launch as user!" 1>&2
  exit 1
fi

GRABBER_ROOTS=(/usr/share/imgbrd-grabber-*)

for R in "${GRABBER_ROOTS[@]}" ; do
  GRABBER_ROOT="$R"
done

CONFIG_DIR="${HOME}"/.Grabber

! [[ -d ${CONFIG_DIR} ]] && mkdir "${CONFIG_DIR}"
! [[ -d ${CONFIG_DIR}/sites ]] && cp -r "${GRABBER_ROOT}"/sites "${CONFIG_DIR}"
! [[ -f ${CONFIG_DIR}/settings.ini ]] && touch "${CONFIG_DIR}"/settings.ini

exec "${GRABBER_ROOT}"/Grabber "$@"
