# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.2

EAPI=7

CRATES="
  adler-1.0.2
  adler32-1.2.0
  aho-corasick-0.7.18
  ansi_term-0.11.0
  arrayvec-0.5.2
  atty-0.2.14
  autocfg-1.0.1
  bitflags-1.2.1
  block-buffer-0.7.3
  block-padding-0.1.5
  bumpalo-3.7.0
  byte-tools-0.3.1
  bytemuck-1.7.0
  byteorder-1.4.3
  cc-1.0.69
  cfg-if-1.0.0
  chrono-0.4.19
  clap-2.33.3
  color_quant-1.1.0
  config-0.11.0
  crc32fast-1.2.1
  crossbeam-channel-0.5.1
  crossbeam-deque-0.8.0
  crossbeam-epoch-0.9.5
  crossbeam-utils-0.8.5
  deflate-0.8.6
  digest-0.8.1
  dyn-clone-1.0.4
  either-1.6.1
  fake-simd-0.1.2
  foreign-types-0.3.2
  foreign-types-shared-0.1.1
  form_urlencoded-1.0.1
  fs_extra-1.2.0
  fuchsia-cprng-0.1.1
  generator-0.7.0
  generic-array-0.12.4
  getrandom-0.2.3
  gif-0.11.2
  git2-0.13.20
  glob-0.3.0
  handlebars-3.5.5
  hashbrown-0.11.2
  heck-0.3.3
  hermit-abi-0.1.19
  idna-0.2.3
  image-0.23.14
  indexmap-1.7.0
  itoa-0.4.7
  jobserver-0.1.22
  jpeg-decoder-0.1.22
  js-sys-0.3.51
  lazy_static-1.4.0
  lexical-core-0.7.6
  libc-0.2.98
  libgit2-sys-0.12.21+1.1.0
  libz-sys-1.1.3
  linked-hash-map-0.5.4
  log-0.4.14
  loom-0.5.1
  maplit-1.0.2
  matches-0.1.8
  memchr-2.4.0
  memoffset-0.6.4
  miniz_oxide-0.3.7
  miniz_oxide-0.4.4
  nom-5.1.2
  num-integer-0.1.44
  num-iter-0.1.42
  num-rational-0.3.2
  num-traits-0.1.43
  num-traits-0.2.14
  num_cpus-1.13.0
  once_cell-1.8.0
  opaque-debug-0.2.3
  openssl-0.10.35
  openssl-sys-0.9.65
  percent-encoding-2.1.0
  pest-2.1.3
  pest_derive-2.1.0
  pest_generator-2.1.3
  pest_meta-2.1.3
  pkg-config-0.3.19
  png-0.16.8
  proc-macro2-1.0.27
  quick-error-2.0.1
  quote-1.0.9
  rand-0.4.6
  rand_core-0.3.1
  rand_core-0.4.2
  rayon-1.5.1
  rayon-core-1.9.1
  rdrand-0.4.0
  regex-1.5.4
  regex-syntax-0.6.25
  remove_dir_all-0.5.3
  rust-embed-5.9.0
  rust-embed-impl-5.9.0
  rust-embed-utils-5.1.0
  rust-ini-0.13.0
  rustversion-1.0.5
  ryu-1.0.5
  same-file-1.0.6
  scoped-tls-1.0.0
  scoped_threadpool-0.1.9
  scopeguard-1.1.0
  semver-0.11.0
  semver-parser-0.10.2
  serde-0.8.23
  serde-1.0.126
  serde-hjson-0.9.1
  serde-transcode-1.1.1
  serde_derive-1.0.126
  serde_json-1.0.64
  sha-1-0.8.2
  shell-words-1.0.0
  simplelog-0.10.0
  state-0.5.2
  static_assertions-1.1.0
  strsim-0.8.0
  strum-0.21.0
  strum_macros-0.21.1
  syn-1.0.73
  tempdir-0.3.7
  termcolor-1.1.2
  textwrap-0.11.0
  thiserror-1.0.26
  thiserror-impl-1.0.26
  tiff-0.6.1
  time-0.1.43
  tinyvec-1.2.0
  tinyvec_macros-0.1.0
  toml-0.5.8
  typenum-1.13.0
  ucd-trie-0.1.3
  unicode-bidi-0.3.5
  unicode-normalization-0.1.19
  unicode-segmentation-1.8.0
  unicode-width-0.1.8
  unicode-xid-0.2.2
  url-2.2.2
  uuid-0.8.2
  vcpkg-0.2.15
  vec_map-0.8.2
  version_check-0.9.3
  vfs-0.5.1
  walkdir-2.3.2
  wasi-0.10.2+wasi-snapshot-preview1
  wasm-bindgen-0.2.74
  wasm-bindgen-backend-0.2.74
  wasm-bindgen-macro-0.2.74
  wasm-bindgen-macro-support-0.2.74
  wasm-bindgen-shared-0.2.74
  web-sys-0.3.51
  webbrowser-0.5.5
  weezl-0.1.5
  widestring-0.4.3
  winapi-0.3.9
  winapi-i686-pc-windows-gnu-0.4.0
  winapi-util-0.1.5
  winapi-x86_64-pc-windows-gnu-0.4.0
  winreg-0.7.0
  yaml-rust-0.4.5
"

inherit cargo

DESCRIPTION="Addon build system for Arma 3"
HOMEPAGE="https://github.com/BrettMayson/HEMTT"
MY_COMMIT="0493af85b2b920a7ca71474b487e1b03f53d9945"
SRC_URI="
  https://github.com/BrettMayson/HEMTT/archive/${MY_COMMIT}.zip
  $(cargo_crate_uris ${CRATES})"

LICENSE="Apache-2.0 BSL-1.0 ISC MIT Fuchsia-CPRNG"
SLOT="0"
KEYWORDS="amd64"
RESTRICT="mirror"


S="${WORKDIR}/HEMTT-${MY_COMMIT}/hemtt-app"


src_install() {
  newbin ../target/release/hemtt-app hemtt
}
